version: '2'
services:
    nginx:
        image: nginx
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/sites-enabled/default/nginx.conf
            - ./nginx/key/nginx.key:/etc/nginx/ssl/nginx.key
            - ./nginx/crt/nginx.crt:/etc/nginx/ssl/nginx.crt
        ports:
            - "8080:8080"
        networks:
            - reverseproxy
    apimanager:
        image: serrodcal/apimanager
        build: ./apimanager
        volumes:
            - ./apimanager/publisher/site.json:/opt/wso2am-2.0.0/repository/deployment/server/jaggeryapps/publisher/site/conf/site.json
            - ./apimanager/store/site.json:/opt/wso2am-2.0.0/repository/deployment/server/jaggeryapps/store/site/conf/site.json
            - ./apimanager/carbon/carbon.xml:/opt/wso2am-2.0.0/repository/conf/carbon.xml
            - ./apimanager/api-manager/api-manager.xml:/opt/wso2am-2.0.0/repository/conf/api-manager.xml
        ports:
            - "9443:9443"
            - "8243:8243"
            - "8280:8280"
            - "9763:9763"
        networks:
            - reverseproxy
networks:
  reverseproxy:
    driver: bridge
