version: '2'
services:
    nginx:
        image: nginx
        volumens:
            - ./nginx/conf/nginx.conf:/etc/nginx/sites-enabled/default/nginx.conf
        ports:
            - "8080:8080"
        networks:
            - reverseproxy
    apimanager:
        image: serrodcal/apimanager
        build: ./apimanager
        ports:
            - "9443:9443"
            - "8243:8243"
            - "8280:8280"
            - "9763:9763"
        networks:
            - reverseproxy
networks:
  reverseproxy:
    driver: bridge
